# Generated by Django 3.1.5 on 2021-03-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField(max_length=40)),
                ('stuname', models.CharField(max_length=40)),
                ('stumail', models.EmailField(max_length=40)),
                ('stupass', models.IntegerField(max_length=40)),
            ],
        ),
    ]
